#!/bin/sh
# Make a series of raw images from SVG rendered strings:
# for the hourly times:
T="0000 0100 0200 0300 0400 0500 0600 0700 0800 0900 1000 1100 1200 1300 1400 1500 1600 1700 1800 1900 2000 2100 2200 2300"
# Each image is 150xH pixels.
# for the locations:
L="Sheffield"
# Each image is 600x110 pixels, 110x600 when rotated onto the screen.

svg() {
  TEXT=$1
  WIDTH=$2
  HEIGHT=$3
  BASE=$(( ($HEIGHT * 8 + 5)/10 ))
  FONTSIZE=$4
  cat > work/"$TEXT".svg <<EOF
<svg
   xmlns:svg="http://www.w3.org/2000/svg"
   version="1.1"
   width="$WIDTH"
   height="$HEIGHT"
  >
    <text
      x="0"
      y="0"
      transform="translate($(($WIDTH / 2)),$BASE)"
      style="text-anchor:middle;text-align:center;font-size:${FONTSIZE}px;font-style:normal;font-weight:normal;line-height:125%;letter-spacing:0px;word-spacing:0px;fill:#000000;fill-opacity:1;stroke:none;font-family:Sans"
  >$TEXT</text>
</svg>
EOF
}

mkdir -p work

for t in $T; do
  svg "$t" 150 25 20
done
for t in $L; do
  svg "$t" 600 110 72
done
