#!/bin/sh
for p in work/*.png; do
  base=$(basename "$p")
  raw=${base%.png}.raw
  pngtopnm "$p" | pnmflip -rotate90 | pnmtopng |
    pngtokobo565 > "rawimage/$raw"
done

cd rawimage
# We copy rather than link because the Kobo filesystem can't
# handle symlinks.
set -- $(cat <<EOF
1384096538_sun-symbol.raw 800.raw
1384096538_sun-symbol.raw clear.raw
1384831400_sun-cloud.raw 801.raw
cloud-2.raw 8.raw
cloud-2.raw cloudy.raw
umbrella-rain.raw 5.raw
umbrella-rain.raw rain.raw
EOF
)
while [ $# != 0 ]; do
  rm -f "$2"
  cp "$1" "$2"
  shift 2
done
